[package]
name = "mutex_comp"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = "0.12.3"
libc = "0.2.164"
atomic-wait = "1.1.0"
[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "mutex_benchmark"
harness = false
